### PR TITLE
fix: Prompt example fixes

### LINKED ISSUE #137: autocomplete prompt example
## autocomplete

- [x] How to identify that there is scroll in the list.
- [x] The scroll is continuous. Cannot identify start/end
- [x] 'option-hightlight.js' => error
- [x] 'option-multiple.js' => select some option, search for something & press enter

### LINKED ISSUE #167: confirm prompt example
- [ ] enquirer-option-default.js => error
image

### PR DESCRIPTION
**Pull request by rajat-sr**
- fix: confirm/enquirer-option-default.js
Call string functions only on string input
Resolves #167 

- fix: autocomplete/option-highlight.js
Resolves #137

### CODE REVIEW

**Comment by rajat-sr** [comment]
@doowb, can you please review this PR?

**Comment by rajat-sr** [comment]
For some reason, the test cases for Mac are failing in Travis CI but they are passing on my local Mac machine. I've seen the same tests failing in other PRs as well. Can you please help me resolve this?

**Comment by doowb** [comment]
@rajat-sr thanks for the PR!

Don't worry about the failing tests right now since those same ones are also failing for some other PRs.
I'll review this soon.

File: examples/confirm/enquirer-option-default.js [hunk 1]
```diff
@@ -9,10 +9,12 @@ prompt({
   initial: 'j',
   default: '(J/n)',
   isTrue(input) {
-    return input.toLowerCase() === 'j';
+    const isString = typeof input === 'string';
+    return isString ? input.toLowerCase() === 'j' : false;
```
Comment (doowb) [inline examples/confirm/enquirer-option-default.js]: I think all we need here is to do `isTrue(input = '') {`

File: examples/confirm/enquirer-option-default.js [hunk 2]
```diff
@@ -9,10 +9,12 @@ prompt({
...
   },
   isFalse(input) {
-    return input.toLowerCase() === 'n';
+    const isString = typeof input === 'string';
+    return isString ? input.toLowerCase() === 'n' : false;
```
Comment (doowb) [inline examples/confirm/enquirer-option-default.js]: I think all we need here is to do `isFalse(input = '') {`

File: examples/autocomplete/option-highlight.js [hunk 3]
```diff
@@ -9,7 +9,7 @@ const { prompt } = require('enquirer');
     type: 'autocomplete',
     name: 'flavor',
     message: 'Pick your favorite flavor',
-    highlight: colors.green,
+    highlight: text => colors.green(text),
```
Comment (doowb) [inline examples/autocomplete/option-highlight.js]:
```suggestion
    highlight: str => colors.green(str),
```
I think using `str` instead of `text` will keep this example consistent with other examples.

File: examples/confirm/enquirer-option-default.js (hunk 1 above)
Comment (rajat-sr) [reply examples/confirm/enquirer-option-default.js]: I tried `isTrue(input = '')`, but it is giving the same error.
This is because `input` also gets Boolean values `true` and `false` which overwrites default `''`.
We want to ensure that `toLowerCase` function is only invoked on string values.

Comment (doowb) [reply examples/confirm/enquirer-option-default.js]: Ah... I see. In that case, we want to make sure Booleans are handled correctly too:

```js
  isTrue(input) {
    return typeof input === 'boolean'
      ? input
      : input.toLowerCase() === 'j';
  },
  isFalse(input) {
    return typeof input === 'boolean'
      ? !input
      : input.toLowerCase() === 'n';
  }
```

I think that should be enough to demonstrate this example.

Comment (rajat-sr) [reply examples/confirm/enquirer-option-default.js]: I agree.

**Comment by doowb** [comment]
LGTM, thanks!
